global:
  scrape_interval: 5s  # Default scrape interval
  
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['192.168.0.189:7001'] # use your IP address : application port number